# Generated by Django 4.0 on 2022-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='업로드 파일'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='업로드 이미지'),
        ),
    ]
